DROP TABLE SQLfi_Asercion_Difusa CASCADE;
DROP TABLE SQLfi_Restriccion CASCADE;
DROP TABLE SQLfi_Vista_Difusa CASCADE;
DROP TABLE SQLfi_Predicado_Condicion CASCADE;
DROP TABLE SQLfi_Modificador_Potencia  CASCADE;
DROP TABLE SQLfi_Modificador_Norma CASCADE;
DROP TABLE SQLfi_Modificador_Trans CASCADE;
DROP TABLE SQLfi_Comparador_Difuso CASCADE;
DROP TABLE SQLfi_Cuantificador_Difuso CASCADE;
DROP TABLE SQLfi_Conector_Difuso CASCADE;
DROP TABLE SQLfi_Conjunto_Trapecio CASCADE;
DROP TABLE SQLfi_Conjunto_Expresion CASCADE;
DROP TABLE SQLfi_Elemento_Escalar CASCADE;
DROP TABLE SQLfi_Elemento_Numerico CASCADE;
DROP TABLE SQLfi_Conjunto_Difuso CASCADE;
DROP TABLE SQLfi_Relacion_Escalar CASCADE;
DROP TABLE SQLfi_Relacion_Num CASCADE;
DROP TABLE SQLfi_Relacion_Difusa CASCADE;
DROP TABLE SQLfi_Dominio_Fecha CASCADE;
DROP TABLE SQLfi_Dominio_Hora CASCADE;
DROP TABLE SQLfi_Dominio_Numerico CASCADE;
DROP TABLE SQLfi_Dominio_Escalar CASCADE;
DROP TABLE SQLfi_Dominio CASCADE;
DROP TABLE SQLfi_Termino_Difuso CASCADE;
DROP TABLE SQLfi_Permiso_GrupoCASCADE; 
DROP TABLE SQLfi_Permiso CASCADE;
DROP TABLE SQLfi_Usuario CASCADE;
DROP TABLE SQLfi_Grupo CASCADE;
DROP TABLE SQLfi_Bd CASCADE; 
DROP SEQUENCE incremento_id_permiso;
DROP SEQUENCE incremento_id_termino;
DROP SEQUENCE incremento_id_restriccion;
DROP SEQUENCE incremento_id_usuario;
